#version: '3.9'
#
#services:
#  postgres:
#    image: 'postgres'
#    container_name: 'java-postgres'
#    entrypoint:
#      - 'POSTGRES_USER=employee'
#      - 'POSTGRES_PASSWORD=qwer'
#      - 'POSTGRES_DB=authentication'
#  app:
#    build:
#      context: ./
#    container_name: 'java-app'
#    ports:
#      - '8080:8080'


version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: qwer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
